server:
  port: 0
spring:
  cloud:
    nacos: # nacos配置中心
      config:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        context-path: /nacos
        file-extension: yml
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
  config:
    import: nacos:nacos-service-blog


