server:
  port: 9999

# 设置日志
logging:
  file:
    name: springboot-log.log
  #    path: D:\\logs
  level:
    root: error
    com:
      example:
        demo:
          controller: trace
          service: info