server:
  port: 8088

template:
  templates:
    - {"templateId":"1","templateFilePath": "C:/application/gitee/JavaLearning/kafka-study-imooc/src/main/resources/template/template.json","active":true}
    - {"templateId":"2","templateFilePath": "C:/application/gitee/JavaLearning/kafka-study-imooc/src/main/resources/template/template.json","active":false}
  template-result-type: 0
  template-result-file-path: "C:/application/gitee/JavaLearning/kafka-study-imooc/src/main/resources/template/templateResult.json"

spring:
  kafka:
    bootstrap_servers: "192.168.52.129:9092"
wechat:
  kafka:
    bootstrap_servers: "192.168.52.129:9092"
    acks-config: "all"
    partitioner_class: ""
## 配置log日志
#logging:
#  # 指定log日志文件