spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_demo?characterEncoding=utf8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # nacos 连接信息配置
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  application:
    name: seata-server-storage
mybatis-plus:
  configuration:
    # 将数据库中的下换线转换成驼峰，比如 user_name -> userName
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 配合 Mybatis 打印日志
logging:
  level:
    com:
      example:
        order: debug
# 设置动态端口
server:
  port: 0